first_name = input("What is your first name? ")
last_name = input("What is your last name? ")
faculty = input("What is your faculty? ")
year = int(input("What is your year? "))
month_of_birth = int(input("What is your month of birth? "))
day_of_birth = int(input("What is your date of birth? "))
year_of_birth = int(input("What is your year of birth? "))
print("\nYour first name is", first_name)
print("Your last name is", last_name)
print("Your faculty is", faculty)
print("Your year is", year)
print("Your month of birth is", month_of_birth)
print("Your day of birth is", day_of_birth)
print("Your year of birth is", year_of_birth)